
server : DrawStateServer.java newnet/Group.java model/LineStroke.java newnet/Host.java newnet/Message.java newnet/MessageType.java util/GroupUtilities.java
	javac MapStratClient.java
	javac DrawStateServer.java
	java  DrawStateServer

.PHONY: clean
clean : 
	rm *.class model/*.class view/*.class util/*.class newnet/*.class controller/*.class


